In [ ]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\student\\AppData\\Roaming\\Python\\Python39\\site-packages\\~umpy.libs\\libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-2bde3a66a51006b2b53eb373ff767a3f.dll'
Check the permissions.



In [ ]:
CORPUS = [
'the sky is blue',
'sky is blue and sky is beautiful',
'the beautiful sky is so blue',
'i love blue cheese'
]

In [ ]:
new_doc = ['loving this blue sky this a blue today', 'I he ff loving an me today']
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [ ]:
X = vectorizer.fit_transform(new_doc)9

In [ ]:
vocabulary=vectorizer.get_feature_names_out()
print(vocabulary)

['an' 'blue' 'ff' 'he' 'loving' 'me' 'sky' 'this' 'today']


In [ ]:
print(X.toarray())
print(X)
print(vectorizer.vocabulary_.get('beautiful'))
print(vectorizer.vocabulary_.get('blue'))

[[0 2 0 0 1 0 1 2 1]
 [1 0 1 1 1 1 0 0 1]]
  (0, 4)	1
  (0, 7)	2
  (0, 1)	2
  (0, 6)	1
  (0, 8)	1
  (1, 4)	1
  (1, 8)	1
  (1, 3)	1
  (1, 2)	1
  (1, 0)	1
  (1, 5)	1
None
1


In [ ]:
bigram_vectorizer = CountVectorizer(ngram_range=(1,2))
analyze = bigram_vectorizer.build_analyzer()
analyze('the sky is blue')

['the', 'sky', 'is', 'blue', 'the sky', 'sky is', 'is blue']

In [ ]:
X1= bigram_vectorizer.fit_transform(CORPUS).toarray()
voc=bigram_vectorizer.get_feature_names_out()
print(voc)
print(X1)

['and' 'and sky' 'beautiful' 'beautiful sky' 'blue' 'blue and'
 'blue cheese' 'cheese' 'is' 'is beautiful' 'is blue' 'is so' 'love'
 'love blue' 'sky' 'sky is' 'so' 'so blue' 'the' 'the beautiful' 'the sky']
[[0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 1 0 1]
 [1 1 1 0 1 1 0 0 2 1 1 0 0 0 2 2 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 1 0 0 1 0 0 1 1 1 1 1 1 0]
 [0 0 0 0 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0]]


In [ ]:
feature_index = bigram_vectorizer.vocabulary_.get('is blue')
print(feature_index)

10


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
'the sky is blue',
'sky is blue and sky is beautiful',
'the beautiful sky is so blue',
'i love blue cheese'
]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print (X)
print (vectorizer.get_feature_names_out())
print(X.shape)

  (0, 2)	0.3992102058196136
  (0, 4)	0.4882913888670788
  (0, 6)	0.4882913888670788
  (0, 8)	0.6031370082211672
  (1, 1)	0.3473079263825201
  (1, 0)	0.44051606615876376
  (1, 2)	0.22987955785181605
  (1, 4)	0.5623513975308212
  (1, 6)	0.5623513975308212
  (2, 7)	0.5479699188774512
  (2, 1)	0.4320257780944028
  (2, 2)	0.2859534358554926
  (2, 4)	0.34976210104278727
  (2, 6)	0.34976210104278727
  (2, 8)	0.4320257780944028
  (3, 3)	0.6633846138519129
  (3, 5)	0.6633846138519129
  (3, 2)	0.34618161159873423
['and' 'beautiful' 'blue' 'cheese' 'is' 'love' 'sky' 'so' 'the']
(4, 9)


In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
pipe = Pipeline([('count', CountVectorizer(vocabulary=vocabulary)),('tfid', TfidfTransformer())])
pipe.fit(CORPUS) #Document-term matrix is calculated & TfidfTransformer evaluates Inverse Document frequency (idf)

print(pipe['count'].transform(CORPUS).toarray()) #Document-term matrix/ Term Frequency (TF)
print(pipe['count'].get_feature_names_out())
print(pipe['tfid'].idf_) #Inverse Document Frequency(IDF)
transformed_array = pipe.transform(CORPUS).toarray() #Evaluates TF-IDF from IDF matrix
print(transformed_array)

[[0 1 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 2 0 0]
 [0 1 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0]]
['an' 'blue' 'ff' 'he' 'loving' 'me' 'sky' 'this' 'today']
[2.60943791 1.         2.60943791 2.60943791 2.60943791 2.60943791
 1.22314355 2.60943791 2.60943791]
[[0.         0.63295194 0.         0.         0.         0.
  0.77419109 0.         0.        ]
 [0.         0.37838849 0.         0.         0.         0.
  0.92564688 0.         0.        ]
 [0.         0.63295194 0.         0.         0.         0.
  0.77419109 0.         0.        ]
 [0.         1.         0.         0.         0.         0.
  0.         0.         0.        ]]
